# Generated by Django 5.2 on 2025-06-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0010_alter_usersettings_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='name',
            field=models.TextField(default='Srivishnu Vusirikala'),
            preserve_default=False,
        ),
    ]
