# Generated by Django 5.2 on 2025-07-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0011_usercredentials_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='forgot_code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='signup_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
