# Generated by Django 5.2 on 2025-07-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0013_shopitems_alter_usernotifications_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='image',
            field=models.TextField(default='https://i.imgur.com/Mw85Kfp.png'),
        ),
    ]
