# Generated by Django 5.2 on 2025-07-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0014_shopitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='token',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercarts',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
