# Generated by Django 5.2 on 2025-07-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0015_usercredentials_token_alter_usercarts_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='avatar',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
