# Generated by Django 5.2 on 2025-07-11 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0017_eventrsvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReceipts',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
