# Generated by Django 5.2 on 2025-07-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0018_donationreceipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='ticket',
            field=models.TextField(null=True),
        ),
    ]
