# Generated by Django 5.2 on 2025-07-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0019_events_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='ticket',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
