# Generated by Django 5.2 on 2025-07-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0020_alter_events_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='admin',
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='role',
            field=models.TextField(default='user'),
        ),
    ]
