# Generated by Django 5.2 on 2025-07-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0021_remove_usercredentials_admin_usercredentials_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='mailing',
            field=models.BooleanField(default=True),
        ),
    ]
