# Generated by Django 5.2 on 2025-08-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0022_usercredentials_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAnnouncements',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
