# Generated by Django 5.2 on 2025-08-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0023_bannerannouncements'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='last_announcement',
            field=models.IntegerField(default=0),
        ),
    ]
