# Generated by Django 5.2 on 2025-09-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0026_userorders_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
