# Generated by Django 5.2 on 2025-10-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0027_shopitems_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationreceipts',
            name='payment_intent',
            field=models.TextField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userorders',
            name='payment_intent',
            field=models.TextField(default='', unique=True),
            preserve_default=False,
        ),
    ]
