# Generated by Django 5.2 on 2025-10-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0028_donationreceipts_payment_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokens',
            name='type',
            field=models.TextField(choices=[('auth', 'auth'), ('fcm', 'fcm')], default='auth'),
        ),
        migrations.AlterField(
            model_name='usertokens',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
