# Generated by Django 5.2 on 2025-10-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0029_usertokens_type_alter_usertokens_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokens',
            name='token',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
