# Generated by Django 5.2 on 2025-10-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0030_alter_usertokens_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='item',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='image',
            field=models.TextField(default='https://i.imgur.com/Mw85Kfp.png'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='name',
            field=models.TextField(default='Illini Dads Can Koozie 16 oz.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='price',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
    ]
