# Generated by Django 5.2 on 2025-10-31 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_app', '0031_remove_orderitems_item_orderitems_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_orders', to='ida_app.shopitems'),
        ),
    ]
